[toolchain]
anchor-lang = "0.29.0"
solana-program = "1.18.22"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zkns = "J4Y18vjQXWtJbo3UNVwyz8MikkGwcqF9sKPhUNBRxZED"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "SySTEM1eSU2p4BGQfQpimFEWWSC1XDFeun3Nqzz3rT7"
program = "programs/zkns/tests/fixtures/light_system_program.so"

[[test.genesis]]
address = "compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq"
program = "programs/zkns/tests/fixtures/account_compression.so"

[[test.genesis]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "programs/zkns/tests/fixtures/spl_noop.so"

[[test.genesis]]
address = "Lighton6oQpVkeewmo2mcPTQQp7kYHr4fWpAgJyEmDX"
program = "programs/zkns/tests/fixtures/light_registry.so"

[[test.genesis]]
address = "cTokenmWW8bLPjZEBAUgYy3zKxQZW6VKi7bqNFEVv3m"
program = "programs/zkns/tests/fixtures/light_compressed_token.so"

[test.validator]
url = "https://devnet.helius-rpc.com/?api-key=a59bcf28-fe9d-4337-8b28-575196ddcb2f"

# Registered program pda
[[test.validator.clone]]
address = "35hkDgaAKwMCaxRz2ocSZ6NaUrtKkyNqU6c4RV3tYJRh"

# Shared Public State Tree
[[test.validator.clone]]
address = "smt1NamzXdq4AMqS2fS2F1i5KTYPZRhoHgWx38d8WsT"

# Shared Public Nullifier Queue
[[test.validator.clone]]
address = "nfq1NvQDJ2GEgnS8zt9prAe8rjjpAW1zFkrvZoBR148"

# Shared Public Address Tree
[[test.validator.clone]]
address = "amt1Ayt45jfbdw5YSo7iz6WZxUmnZsQTYXy82hVwyC2"

# Shared Public Address Queue
[[test.validator.clone]]
address = "aq1S9z4reTSQAdgWHGD2zDaS39sjGrAxbR31vxJ2F4F"
