[toolchain]
anchor-lang = "0.29.0"
solana-program = "1.18.22"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zkns = "J4Y18vjQXWtJbo3UNVwyz8MikkGwcqF9sKPhUNBRxZED"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "SySTEM1eSU2p4BGQfQpimFEWWSC1XDFeun3Nqzz3rT7"
program = "test-programs/light-system-program.so"

[[test.genesis]]
address = "compr6CUsB5m2jS4Y3831ztGSTnDpnKJTKS95d64XVq"
program = "test-programs/account-compression.so"
